### PR TITLE
Implement API that allows providing data for modules.

### PR DESCRIPTION
**Pull request by plusvic**
Most YARA modules use the data being scanned as their only input, but some others needs additional data (example: the "cuckoo" module). With the existing API the user didn't have a way for providing additional data to modules. This commit implements a new set of API functions that accept a ScanOptions structure, where one the fields is a map of strings to byte slices that provides additional data for modules.

As the new API is more general, the existing functions where implemented using the new ones.

### CODE REVIEW

**Comment by hillu** [comment]
Thank you. It may take some days for me to decide what to do with this PR because I have plans for potentially incompatible API changes (that would more or less expose the C API callback interface) which would warrant bumping the version number to 2.x.

**Comment by plusvic** [comment]
That would be great. I'm using go-yara for a project in VirusTotal and it works great. I just missed this feature, but in the meantime I can keep using my own fork until you release version 2.x.

**Comment by hillu** [comment]
@plusvic what do you think about the work I have pushed to the rules-callback branch?

**Comment by plusvic** [comment]
I like the approach. But I recommend you waiting a little bit before releasing it. I'm starting to implement some new functions in the YARA API for solving https://github.com/VirusTotal/yara/issues/350. It's similar to https://github.com/VirusTotal/yara/pull/559 but making use of `YR_SCAN_CONTEXT` instead of defining a new kind of context. I should have it working in a week or two.

**Comment by plusvic** [comment]
Hi @hillu, take a look at https://github.com/VirusTotal/yara/commit/be0fc3f52f140d38a6a45db006ddc2b71d4de825. That's the new API I mentioned in the previous comment. I think it's worth using it for the new version of go-yara as it solves the problem of using the same rules for scanning multiple files with different sets of external variables. The change consists in introducing another object named `YR_SCANNER`. You can create multiple `YR_SCANNER` objects for the same `YR_RULES`, and `YR_SCANNER` has `yr_scanner_scan_*` and `yr_scanner_define_*_variable` functions similar to `yr_rules_scan_*` and `yr_rules_define_*_variable` respectively.

**Comment by plusvic** [comment]
For `go-yara` you could replicate the same API, by introducing a `Scanner` type that could be used like:

```
r, _ := yara.Compile(rules, variables)
s := yara.NewScanner(r)
s.DefineVariable("foo", 1)
s.DefineVariable("bar", 2)
s.SetTimeout(60*time.Seconds)
s.SetCallback(cb)  // change the default stdCallbackData to something else.
matches, _ := s.ScanMem(r)
```

The `ScanX` methods for `Rules` could be even removed if you want a simpler API. That way users won't be confused by the multiple forms of doing the same thing. What do you think?

**Comment by hillu** [comment]
Thanks for the heads-up!

I should be able to use the rules-callback branch pretty much as-is.

**Pull request closed without merging**
