### PR TITLE
Add Windows installation doc

### PR DESCRIPTION
**Pull request by codeyourweb**
Added specific documentation for libyara, go-yara and dependencies compilation and install on Windows

### CODE REVIEW

**Comment by hillu** [comment]
Thank you, I really appreciate this.

I'd like to include something a bit simpler in the main README. I guess I'll try your description on a Windows VM in the next few days. With some luck, there might even be a way to provide simple Windows-based build instructions for [Spyre](/spyre-project/spyre).

**Comment by hillu** [comment]
@codeyourweb I have added some documentation mentioning MSYS2 and added an example to `README.cross-building.md` in #80. This is quite a bit shorter than your suggestion. Do you think that this example would have helped you if it had existed 3 weeks ago?

**Comment by codeyourweb** [comment]
👍 indeed, it will help a lot

**Comment by hillu** [comment]
okay, I am closing this PR then. Thank you for doing the hard trial&error work that led to the description.

**Pull request closed without merging**
