### PR TITLE
Implement Finalize() function

### PR DESCRIPTION
**Pull request by plusvic**
This is the first one of a series of PR that I intend to submit in order to reduce the gap between this repository and a separate [fork](https://github.com/plusvic/go-yara) I've been using until now and that has diverged from this one over time. My intention is to reach feature parity with that fork and start using this one as the canonical `go-yara` package.

### CODE REVIEW

**Comment by hillu** [comment]
Awesome, thank you in advance! BTW, I am working on the Scanner API, so I expect to release a go-yara 1.1 (or 2.0, depending on whether I add breaking changes) in the next few days.

**Comment by plusvic** [comment]
I've implemented the Scanner API in https://github.com/plusvic/go-yara/blob/master/scanner.go. You can take ideas from there or copy the code altogether. That was one of the PR I was planning to submit.

**Comment by plusvic** [comment]
I think this should be solved by applying PR #33. I had a similar issue in the past and the problem was that the Compiler wasn't being explicitly destroyed in the Compile function. This specific commit worked for me:
 https://github.com/hillu/go-yara/commit/0babae5f5200ac8a07a5606824ae70d629c0e0f9

**Comment by hillu** [comment]
I have integrated the last change in bc03d0a3e173a743d8ae247719817fcbd838c496. Closing this PR. Thank you!

**Pull request closed without merging**
