### PR TITLE
Added code to work on power system

### PR DESCRIPTION
**Pull request by genisysram**
Hi
This is my contribution to your code, added code to run on power Systems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by hillu** [comment]
Thanks for your PR.

I don't really see what is gained by testing go-yara on a differnt architecture. In my experience so far, any cross-architecture portability issues have been in YARA itself. Am I missing something?

**Comment by genisysram** [comment]
Tagging @gerrith3 to respond for your query.

**Comment by hillu** [comment]
@genisysram I am not going to merge your PR since I still don't see the benefit. I have spent way too much of my lifetime fighting syntax, semantics, and undocumented behaviors of CI systems already, Travis CI in particular.

**Comment by genisysram** [comment]
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

**Comment by hillu** [comment]
I understand what your patch does, I just don't see any value in it, therefore I am not merging it.

Besides, Ubuntu already contains go-yara (package golang-gtihub-hillu-go-yara-dev).

**Comment by gerrith3** [comment]
Hi @hillu we are moving as much testing sooner in the process than just the debian and ubuntu build farms now that we have Travis CI and reducing our investment in testing there.  All access to Travis CI for Power is free for open source use.  This patch ensures that both the entire build time environment and all dependencies are present in the ppc64le environment and that tests pass as expected on actual hardware.  We'd appreciate if you re-considered.  Thanks!

**Comment by hillu** [comment]
The cycles would be better spent on testing YARA itself.

**Comment by gerrith3** [comment]
@genisysram can you look into @hillu's recommendation above and see if you can do that?

**Pull request closed without merging**
